[tool.black]
line-length = 120
target-version = ['py312']
extend-exclude = '''
/(
    \.git
  | \.github
  | \.idea
  | \.local
  | \.mypy_cache
  | \.venv
)/
'''

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_sort_within_sections = true
atomic = true
